version: 0.0
os: linux
files:
  - source: /
    #destination: /var/www/html/
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: stop_server
      timeout: 30
      runas: root